### ISSUE TITLE
What can I do to debug this extension when it's not working?

### ISSUE THREAD

**Issue by johnbillion** [neild3r/vscode-php-docblocker#102]
Thanks for this extension, it's one of those that you get so used to having that it's weird when it doesn't work.

I recently set up a new machine from scratch and this extension is no longer adding `@param` and `@return` tags when adding a docblock above an existing function or method.

What can I do to debug the problem? Cheers!

**Comment by neild3r** [comment]
It's probably something simple like you aren't getting the snippet presented to you automatically. I'd first try summoning the snippets manually by typing /** then doing the trigger suggest shortcut. For me it's ctrl + space (OSX)

**Comment by johnbillion** [comment]
You're right, triggering the snippet manually with ctrl+space immediately after the opening `/**` brings up the PHP DocBlocker snippet, and when I select that it correctly populates the tags as expected.

I'll dig around my Code settings and see what's preventing the snippet from triggering automatically.

**Comment by neild3r** [comment]
This relates to #44. We just need a bit of docs around settings and how it works. The most recent release has the ability to trigger via a command as well so a section on triggering it the docs would be useful.

**Comment by johnbillion** [comment]
`suggestOnTriggerCharacters` was indeed the cause of my problem.
