### ISSUE TITLE
Support parameter defaults in @method & @param?

### ISSUE THREAD

**Issue by nmsmith22389** [neild3r/vscode-php-docblocker#107]
If possible I would love to have support for parameter defaults (ie `function foo($bar = 'bam')`) in the `@method` and `@param` tags.
It seems like this does work when it's inferring from the method itself but you can't explicitly specify them. *(although doing it with no spaces does seem to sort of work)*

Thanks! 😀

**Comment by neild3r** [comment]
I believe this is supported already so closing for now
