### ISSUE TITLE
Running the contributed command: 'php-docblocker.trigger' failed.

### ISSUE THREAD

**Issue by aaly00** [neild3r/vscode-php-docblocker#108]
After the latest VS Code update, I have been getting this error. 
I change the php path from PHP5 to PHP7.3, but I am not sure if that's related since the extension doesn't require dependencies AFAIK. 
![image](https://user-images.githubusercontent.com/11652379/56376534-bb4bae80-61cd-11e9-815d-8e5cd4f1415a.png)

VS Code version: 
![image](https://user-images.githubusercontent.com/11652379/56376564-cd2d5180-61cd-11e9-9b4c-6590000f615d.png)

Tried reloading. Uninstalling then reloading.
I also tried to reboot the machine.

**Comment by neild3r** [comment]
This command only works if your cursor is on the line above a Function or Class where exactly are you triggering running the tigger command?

**Comment by afroty** [comment]
This is a file I created somefile.php 
![image](https://user-images.githubusercontent.com/11652379/56506353-cbbc9b80-64e3-11e9-90ea-c22e30e2940d.png)

I trigger the command where the cursor is shown. Throws the error.

**Comment by neild3r** [comment]
Probably because the plugin was designed for class based functions which start with a visibility (private, public, protected) your function doesn't have a visibility so it's not triggering. It could be possible to make it so that it can handle functions outside of classes.

**Comment by gotchapt** [comment]
I'm having the same problem on a function with visibility, since the last VSCode update. I'm on VSCode 1.36.0.
It still works for `class`

**Comment by neild3r** [comment]
@gotchapt Can you please give an example of a function you are trying to trigger the docblock on that is not working? It is working for me

**Comment by gotchapt** [comment]
> @gotchapt Can you please give an example of a function you are trying to trigger the docblock on that is not working? It is working for me

Just found out the issue, I forgot how to php 😅 
Was declaring a function like
```
public function appendGroupRequestData(
  array & $availabilities
)
```
instead of 
```
public function appendGroupRequestData(
  array &$availabilities
)
```
