### ISSUE TITLE
Add support for PHPUnit annotations

### ISSUE THREAD

**Issue by martinbean** [neild3r/vscode-php-docblocker#110]
Is it possible to recognise PHPUnit annotations as a DocBlocks (i.e. `@dataProvider`, `@testdox`, etc)?

If you didn’t want to add vendor-specific annotations to the core package, it might be worthwhile adding a configuration option to allow users to specify a list of items that should be treated as DocBlock annotations, and I could then add PHPDoc annotations to that list. Something like:

```json
{
    "php-docblocker.custom-tags": [
        "dataProvider",
        "testdox"
    ]
}
```
```php
/**
 * @dataProvider someDataProviderName
 * @testdox Tests foo
 */
public function testFoo(): void
{
    //
}
```

PHPUnit annotations reference: https://phpunit.readthedocs.io/en/8.1/annotations.html

**Comment by neild3r** [comment]
This has been added by @goodjack via #114
