### ISSUE TITLE
Mark deprecated methods functions in classes

### ISSUE THREAD

**Issue by XanatosX** [neild3r/vscode-php-docblocker#112]
If a class in a library is marked as deprecated and I do use this function in another class or script it would be nice if the method is getting a strikethrough.

This would help a lot with detecting the use of deprecated methods, classes and traits.

Maybe there is a setting I did not notice for this already.

**Comment by neild3r** [comment]
@XanatosX I don't believe this request is applicable to this package. This only writes the docblocks not handles display of them in other files this should be part of an intellisense package.

**Comment by XanatosX** [comment]
I think you are totally right ... Sorry for the late answer
