### ISSUE TITLE
Template order not working

### ISSUE THREAD

**Issue by EneMarine** [neild3r/vscode-php-docblocker#117]
Hello,

I tried to set a functionTemplate but it doesn't seem to be working.
All I get is the default Template.

Here is my settings : 
```
"php-docblocker.extra": [
        "@version",
        "@author Marine"
    ],
    "php-docblocker.functionTemplate": {
        "message": {
            "gapAfter": true
        },
        "extra": {
            "gapAfter": true
        },
        "param": {},
        "return": {},
    },
```

And Here is the outcome 
```
/**
   * Undocumented function
   *
   * @param array $meta_fields
   * @return void
   * @version
   * @author Marine
   */
```

**Comment by neild3r** [comment]
@EneMarine thank you for raising this. You are correct I will look into this

**Comment by neild3r** [comment]
@EneMarine I have a fix ready. I'll do a bit more testing tonight and hopefully release the patch tomorrow

**Comment by neild3r** [comment]
Just to confirm the fix has now been released.
