### ISSUE TITLE
Add @mixin tag

### ISSUE THREAD

**Issue by ycs77** [neild3r/vscode-php-docblocker#120]
I hope you can add @mixin tag so that class can mixin other class methods hints.

My use time is to call `SecondClass` in the `__call` method on `FirstClass`.

Use example:
```php
/**
 * @mixin SecondClass
 */
class FirstClass
{
    //
}
```

Can this be achieved?

**Comment by paul-a-byford** [comment]
Is there any plans for this?

**Comment by tianyiw2013** [comment]
I think it's a good suggestion.

**Comment by besrabasant** [comment]
Aboslutely... When can we expect this feature to be added?

**Comment by StevenRoan** [comment]
also need this feature or do we have any workaround?

**Comment by dvsoukup** [comment]
Seems like slightly old thread but... I saw this PR:
#135 

Looks like it just has a failing test.  I too would like these doc tags added.

**Comment by neild3r** [comment]
This was implemented
