### ISSUE TITLE
[feature request] Lint for docblock correctness

### ISSUE THREAD

**Issue by johanvanhelden** [neild3r/vscode-php-docblocker#125]
It would be great if the plugin could check a docblock for correctness. For example:

```
    /**
     * Update the invitation.
     *
     * @param Request $requests
     *
     * @return \Illominate\View\View
     */
    public function update(UpdateRequest $request)
    {
```

Should result in 3 linting errors. Because:
- The `@return` FQN does not exist. It should be `\Illuminate\View\View`
- The `@param` is incorrect, because `$requests` should be `$request`
- The `@param` is incorrect, because `Request` should be `UpdateRequest`

**Comment by tianyiw2013** [comment]
I suggest you use the `PHP intelephense` extension in vscode.

**Comment by johanvanhelden** [comment]
Alright, so out of scope for the docblocker extension :+1:
