### ISSUE TITLE
Return void

### ISSUE THREAD

**Issue by fatoon29** [neild3r/vscode-php-docblocker#137]
Hello,
When i use the docBlock, it always put Return void enven if i had a a return with a param.
How to fix that ?
thanks and btw, good job :D

**Comment by neild3r** [comment]
Hi @fatoon29,

There's a config option called `returnVoid` which if you set to false it will turn it off

**Comment by svivian** [comment]
But that option removes the `@return` entirely. I think their point is that it should put the actual type in there. It still shows void for a simple function like this:

	public function example()
	{
		return 'string';
	}

But it should put `@return string`.

**Comment by neild3r** [comment]
@svivian as the package doesn't parse the entire function only the head it is not possible to do that. Really you should be type hinting your return which is catered for.

```php
public function example(): string
{
    return 'string';
}
```

**Comment by patrickvlt** [comment]
> 
> 
> @svivian as the package doesn't parse the entire function only the head it is not possible to do that
> 


Are you planning to add this functionality in the future? This would be extremely helpful.

**Comment by neild3r** [comment]
Unfortunately not I think doing that would be a different package that is based on something a lot more sophisticated than regex's
