### ISSUE TITLE
Parameter is null

### ISSUE THREAD

**Issue by diosby** [neild3r/vscode-php-docblocker#140]
I have function public function setMarginsFromArray(array $array = null)

The description was generated:
/**
     * Undocumented function
     *
     * **@param array $array**
     * @return void
     */

I expect the following description (php 7.0):
/**
     * Sets margins from the array.
     *
     * **@param  array|null $array**
     * @return void
     */
    public function setMarginsFromArray(array $array = null)

**Comment by umairkhan-dev** [comment]
You have to tell that this param may be `null` or `array` like
See the `?` before `array` _(type)_ in `public function test(?array $array=null)`
```
    /**
     * Undocumented function
     *
     * @param array|null $array
     * @return void
     */
    public function test(?array $array=null)
    {
        # code...
    }
```

**Comment by neild3r** [comment]
This is supported as of v2.3.0
