### ISSUE TITLE
Question: Example for default php-docblocker.author

### ISSUE THREAD

**Issue by izual36** [neild3r/vscode-php-docblocker#141]
Hey, i'm relatively new to JSON. I don't know wich keys i have to define in the php-docblocker.author setting. I think it has at least two keys. 

Would be awesome if somebody could give me an example for the complete JSON 
php-dockblocker.author {} setting. 

Thanks in advance.

**Comment by Vilochane** [comment]
Hi, try this if it works for you, go to your vs code settings.json. 
or go to, File->Preferences->Settings->UserTab(By Defafult it's already selected)->Extentions->PHP-docblocker->PHP-docblocker: Class Template

Eg:

``` json
  "php-docblocker.classTemplate": {
    "author": {
      "content": "@author ${###:FirstName SecondName} <${###:your-email}>"
    }
  }

**Comment by mehedi101** [comment]
add this code on setting.json file
`"php-docblocker.author": {
        "name": "Mehedi Hasan",
        "email": "hello@mehedihasn.com"
    }`

**Comment by neild3r** [comment]
Closing as this question was answered
