### ISSUE TITLE
Not working on My Vscode System version 1.46.1

### ISSUE THREAD

**Issue by dimaslanjaka** [neild3r/vscode-php-docblocker#142]
![image](https://user-images.githubusercontent.com/12471057/85237531-d826e600-b451-11ea-9fc7-b7a1921db4b1.png)

before vscode version, still working.

OS: windows 10

**Comment by neild3r** [comment]
Closing this for now as I have not received more widespread feedback for issues. Very sorry this has gone unanswered for so long but please re-open if you want to continue to help debug the problem
