### ISSUE TITLE
DocBlock not generating for function having associative array as param with more than 1 value

### ISSUE THREAD

**Issue by umairkhan-dev** [neild3r/vscode-php-docblocker#143]
DocBlock not generating for function having associative array as param with more than 1 value.
Here is the code
```
<?php
class test
{
    
    public function test1(array $options = [])
    {
        # code...
    }
    
    public function test2(array $options = ['a' => 123])
    {
        # code...
    }
    
    public function test3(array $options = ['a' => 123, 'b' => 456])
    {
        # code...
    }
}
```
The DocBlock is generated for first two functions but not for third.
![PHP DocBlock Issue](https://user-images.githubusercontent.com/16460954/86893646-602c1180-c11b-11ea-8d23-bcfc45453c59.gif)

**Plateform Details:** **PHP DocBlocker** Version: 2.1.0, **Visual Studio Code** Version: 1.46.1 (system setup) on **Windows 10 Pro** Version: 2004

**Comment by umairkhan-dev** [comment]
@neild3r Is this project dead...?

**Comment by neild3r** [comment]
@umairkhan-dev no I just haven't had any time to work on it as I've been extremely busy

**Comment by umairkhan-dev** [comment]
As the author of this extension is not active for some time. Also, I have switched to [PHP DocBlocker2](https://github.com/tianyiw2013/vscode-php-docblocker).
I am closing this.
