### ISSUE TITLE
No docblock hints when hovering

### ISSUE THREAD

**Issue by davidfrp** [neild3r/vscode-php-docblocker#148]
I no longer get hints when I peek with the mouse. It merely tells me its general description, but nothing about return types or their descriptions.

![image](https://user-images.githubusercontent.com/6499570/97436508-66d8d180-1922-11eb-911f-36710c403349.png)

**Comment by neild3r** [comment]
This package does not handle that. This is up to intellisense to handle. This package just helps with the writing of the block itself.

**Comment by davidfrp** [comment]
Oh sorry. I've now installed some proper PHP intellisense, and it seems really eager to tell me twice now 😅 

![image](https://user-images.githubusercontent.com/6499570/97451259-df945980-1933-11eb-9f17-21993de23823.png)
