### ISSUE TITLE
Suddenly not getting an asterisk (*) on a new line within the block

### ISSUE THREAD

**Issue by Bl4ckread** [neild3r/vscode-php-docblocker#151]
This extension used to work great for me, but as of today I'm suddenly not getting an asterisk (*) inserted automatically whenever I do a new line (press enter) within a docblock. I haven't done any changes in my environment, but maybe there has been an update either to this extension or something else that conflicts with this extension? Other than this issue the docblocks are still generated just as before.

Everything was working fine last sunday, so this has cropped up since then.

**Comment by neild3r** [comment]
This was removed from this plugin as it started built into vscode as standard

**Comment by tanc** [comment]
Sorry to comment on a closed issue but where is this setting in vscode? It's the one thing that drives me crazy, that a newline within a dockblock breaks the dockblock instead of adding a ` *`
