### ISSUE TITLE
Should we move to support multiple languages?

### ISSUE THREAD

**Issue by neild3r** [neild3r/vscode-php-docblocker#17]
It wouldn't be that hard to support additional languages? Few things worth noting.

- Already a docblockr that works well with js/typescript so should we bother with that?
- What other languages should be included?
- We probably need people to contribute their languages so better code documentation would be required
- Limits how deep we can go improving the PHP support, or does it? Can we move to tokenizers within each language in future?
- Could we somehow leverage the syntax highlighting to help us parse code to make it easier to port to other languages?
- How do we handle the rename of the extension.

**Comment by Xety** [comment]
If would be nice if it could work for the Zephir lang. It's very similar to PHP.
https://zephir-lang.com

**Comment by neild3r** [comment]
I'm familiar with it, I've done some work on Phalcon in the past, good suggestion.

**Comment by joelday** [comment]
@neild3r I have a private branch where I was working on a multi-language solution for vscode-docthis. There are some interesting challenges for sure. Been too busy to go forward with it much.

**Comment by CallMeSirLiu** [comment]
same PR

**Comment by lmajano** [comment]
I would love to help with ColdFusion/CFML support

**Comment by ta-riq** [comment]
Can i help to convert my favorite extension  to my native language ? 

> Bangla

**Comment by bourdin07** [comment]
Ungroup parameters tags and return tag

**Comment by darighteous1** [comment]
Custom tags and coloring options would be nice

**Comment by nezaboravi** [comment]
Possibility to keep @return tag as last tag in docblock.

**Comment by kAlvaro** [comment]
I particularly prefer addons that do one thing and do it well. As of today this is the PHP docblock extension that seems to works best and it still can use improvements in certain areas (such as @throws generation). Just my opinion ;-)

**Comment by joseffb-mla** [comment]
Add custom @used-by tag and have the extension scour the code to autofill references. Would also like it to do this for the @uses tag as well.

**Comment by televators** [comment]
@joseffb-mla Same! I know I'm dredging old issues but I am getting into documenting my stuff better and using phpDocumentor and they support the \@used-by tag as well as \@uses and generates links between all associated structures in the documentation it creates. Plus having both \@uses and \@used-by would provide some contextual data for other plugins to use in interpreting and jumping around.
