### ISSUE TITLE
[Feature] Make this extension available for VSCode web or Codespace

### ISSUE THREAD

**Issue by shivapoudel** [neild3r/vscode-php-docblocker#176]
I'm often using VSCode web on GitHub and would love to have the same feature available.

Ref: PKief/vscode-material-product-icons#20 (comment) and microsoft/vscode#130628

CC @neild3r @tianyiw2013

**Comment by tianyiw2013** [comment]
I can't experience codespace, Can you temporarily join me in your organization? I want to have a test.

**Comment by neild3r** [comment]
I've got it to the point where it's installable but producing an error will see if it can be solved looking at vscode-test-web

**Comment by neild3r** [comment]
Looks like the problem is we are loading the fs module in one of the helpers which is supposed to aid in unit testing. We just need to move that code to the tests directory

**Comment by neild3r** [comment]
The new release v2.2.3 should now work in github 🎉
