### ISSUE TITLE
Default `mixed` as unknown type, replace `[type]`

### ISSUE THREAD

**Issue by tianyiw2013** [neild3r/vscode-php-docblocker#177]
PHP uses mixed instead of any type, I think we should completely change `[type]` to `mixed`.

What's your opinion?

**Comment by neild3r** [comment]
I think we want this to be configurable as I can see why people would want it.

However, I think just defaulting to mixed in some cases may encourage people to be lazy. With more type hinting being possible in more modern PHP we shouldn't really be relying on mixed anyway.
