### ISSUE TITLE
When active, intellisense variables list doesn't work

### ISSUE THREAD

**Issue by adzchappers** [neild3r/vscode-php-docblocker#20]
I've noticed that when I have this package active, Intellisense no longer suggest variables from within the page in the list, just defaults to the functions

With PHP DocBlocker on:
![image](https://cloud.githubusercontent.com/assets/611127/24397738/14e4534a-139f-11e7-8cdc-77e1f3c6946e.png)

With PHP DocBlocker off: 
![image](https://cloud.githubusercontent.com/assets/611127/24397792/3601b11c-139f-11e7-882a-9cd252cd3de9.png)

**Comment by neild3r** [comment]
Thanks for the update. I will investigate later on tonight, off the top of my head I believe vscode should allow multiple completion suggesters so not sure what the issue might be.

**Comment by adzchappers** [comment]
After playing a bit more, I've noticed that if I just put in a $ I get some sort of variable list (although this doesn't include all the variables it should)

![image](https://cloud.githubusercontent.com/assets/611127/24398717/688d5250-13a2-11e7-9854-e48695c09b0a.png)

But as soon as I try to complete the suggestions then it breaks.

**Comment by neild3r** [comment]
@adzchappers would you be able to clarify which plugin you are using for the intellisense and which version of vscode you are on. I had a quick go with the PHP Intellisense plugin and I found it to work with docblockr on and off.

Would you also be able to tell me what settings you are using such as tab completions and quick suggestions etc?

**Comment by adzchappers** [comment]
Hi @neild3r 

Mac - OS X El Capitan - 10.11.6
VS Code - 1.10.2
PHP DocBlocker 0.4.0
using the built in intellisense.

Windows 10 Pro 
Version - 1607
OS Build - 14393.953
VS Code - 1.10.2
PHP DocBlocker 0.4.0
using the built in intellisense.

On the above two I've disabled every plugin except DocBlocker, reloaded and I'm still getting the same issue.



First time install of Code onto a machine that's never had it on:
Windows 10 Pro 
Version - 1607
OS Build - 14393.953
VS Code - 1.10.2
PHP DocBlocker 0.4.0
using the built in intellisense.

When I hit $ and start typing, I lose variable scope and only get php functions.

**Comment by neild3r** [comment]
Hi @adzchappers,

Thanks for the update. I have been able to replicate now and believe I know what the issue is I just need to work out the best way to solve it without breaking this extensions enter rules. Hopefully have a fix later today.

**Comment by neild3r** [comment]
Hi @adzchappers,

This should now be fixed in v0.4.1!

**Comment by adzchappers** [comment]
Thanks @neild3r it does appear to be working on all three of my installations now!

Nice one!
