### ISSUE TITLE
Continuation of DocBlock when pressing enter when in a DocBlock

### ISSUE THREAD

**Issue by tanc** [neild3r/vscode-php-docblocker#218]
One of the stated features of this extension is "Continuation of DocBlock when pressing enter when in a DocBlock"

This doesn't work for me and I'm not sure why. Whenever I hit enter/return within a DocBlock it enters a newline character instead of ` *` which breaks the DocBlock.

In #151 it was stated "This was removed from this plugin as it started built into vscode as standard" but when disabling all extensions and trying a new line within a DocBlock the same problem occurs.

Is there a specific VSCode setting to enable this?

**Comment by neild3r** [comment]
You can see the PR to remove it here #62

**Comment by tanc** [comment]
Thank you so much for the information. I've now tracked down my issue to a vscode setting:
`"editor.autoIndent": "brackets",`

Changing this to 'advanced' or 'full' seems to have fixed it:
`"editor.autoIndent": "advanced",`
