### ISSUE TITLE
@see Shows 'undefined'

### ISSUE THREAD

**Issue by wileycoyote78** [neild3r/vscode-php-docblocker#243]
I am probably doing something wrong, so this is probably not an "issue" outside of ID-10-T. 

Using @see comes up as undefined, even though the (in this case) function/method is defined.

![code](https://github.com/user-attachments/assets/8396e448-ed69-43a7-8ede-1a6514b1bf4f)
![code_2](https://github.com/user-attachments/assets/17e1f413-69b2-499f-9d7b-5241fb0b0c1a)

Like I said, I am probably doing something wrong, but I cannot figure out what. Any pointers for this obvious noob would be much appreciated.

**Comment by neild3r** [comment]
The only pointer I can give you is that this is unrelated to this package. This only generates the docblocks it doesn't provide that overlay that must be some intellisense package

**Comment by wileycoyote78** [comment]
Very well. I will look into it. Thank you for the pointer.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by wileycoyote78** [comment]
I should have payed more attention... yes, it is an [issue](https://github.com/bmewburn/vscode-intelephense/issues/1316) with the Intelephense extension. Sorry to have troubled y'all. Marking as closed.
