### ISSUE TITLE
If the method has no parameters, auto complete failure

### ISSUE THREAD

**Issue by MarlonFan** [neild3r/vscode-php-docblocker#3]
System: MacOS 10.12
VSCode Version: 1.10.2
Repetition:

Press the enter key

![image](https://cloud.githubusercontent.com/assets/9349370/23945968/7fa08f28-09b3-11e7-9cb1-cf9c2bc5348d.png)

**Comment by neild3r** [comment]
This is a regression and will be fixed very soon.

**Comment by neild3r** [comment]
This should now be fixed #4
