### ISSUE TITLE
HOW TO USE php-docblocker.extra

### ISSUE THREAD

**Issue by unosky** [neild3r/vscode-php-docblocker#30]
I've tried to use  

>     "php-docblocker.extra": ["version","created"] 
 but It didnt worked

**Comment by neild3r** [comment]
Would you be able to post a screenshot that shows the problem you are having?

The expected output from that setting for say a class would be.

```
/**
 * Undocumented  class
 * version
 * created
 */
```

What's the output you are wanting?

**Comment by neild3r** [comment]
Closing until we have more info
