### ISSUE TITLE
Issue when using type hints and classes with full namespace references

### ISSUE THREAD

**Issue by to2false** [neild3r/vscode-php-docblocker#32]
I follow the document said, but it doesn't work. It can work above class and over function with a new line.

**Comment by neild3r** [comment]
I don't understand. Could you submit some screenshots to help me understand what you mean?

**Comment by to2false** [comment]
![image](https://cloud.githubusercontent.com/assets/21302817/25209180/f76614b0-25ab-11e7-908e-c5bc1b303bf7.png)

![image](https://cloud.githubusercontent.com/assets/21302817/25209188/0646ae5e-25ac-11e7-91fd-d30f0d825257.png)

**Comment by neild3r** [comment]
Thanks, it could be the \ in the type hint let me try it it out and see if I can replicate

**Comment by neild3r** [comment]
OK I've replicated the issue, I'll add some test cases now and see if we can get this sorted for you. I've never had the issue because I always use use statements even for root classes

**Comment by neild3r** [comment]
The fix has now been merged, I was planning on releasing a new version today so this will be included within

**Comment by to2false** [comment]
Thank you. :smile:

**Comment by neild3r** [comment]
No problem, the new version has now been released so you should be able to get the update soon. Thanks for raising the issue.
