### ISSUE TITLE
Use tabs in param tags

### ISSUE THREAD

**Issue by jens1o** [neild3r/vscode-php-docblocker#35]
Hi,

first of all: Thanks, this a very useful tool!

Personally, I have a `tab`(up to 4 spaces) before and after each part in the `param` tag. But this is missing here. Would it be possible to add this?

That's what I am expecting:
![image](https://cloud.githubusercontent.com/assets/11234139/26036980/cf311aca-38e9-11e7-8205-b2a21310d3f1.png)

Regards!

**Comment by neild3r** [comment]
Hi @jens1o,

You are quite welcome, glad you are finding it useful.

Just to clarify. I'm assuming you want a description placeholder adding to the `@param` tag or at least a config option to turn it on?

**Comment by jens1o** [comment]
Oh, sorry, this is a very bad typo. I mean tab. So each entity in the `param` tag has a Tab before it, so it is the same in all param tag and it is still clear.

**Comment by neild3r** [comment]
I would suggest this is more parameter alignment which was planned and also requested as part of #37

**Comment by jens1o** [comment]
okay, as long as I can freely set parts before each entity, I'm fine!
