### ISSUE TITLE
Allow to specify default content for @author

### ISSUE THREAD

**Issue by neufena** [neild3r/vscode-php-docblocker#36]
Allow to add default content so a dev can add their name and email once then it's auto inserted to this extension

**Comment by neild3r** [comment]
Hi @neufena,

You can just use the extra config option to do this. It's what I do, in my vscode settings I have something like the below.

```json
    "php-docblocker.extra": [
        "@author Neil Brayfield <neil@email.com>"
    ],
```

**Comment by neufena** [comment]
Great as a workaround for adding a new docblock however it would be ideal id when typing @auth.... into an existing docblock it would allow you to autocomplete this to your default value.

**Comment by neild3r** [comment]
You have a point but you could be filling in on behalf of another user, perhaps I could provide a special snippet that is your author but also have the vanilla one for others but this is a separate issue
