### ISSUE TITLE
Allow to align @param lines

### ISSUE THREAD

**Issue by neufena** [neild3r/vscode-php-docblocker#37]
Also support @param comments.  IE

    /**
    * Undocumented function
    *
    * @param string             $string String Comment
    * @param bool               $bool   Boolean Comment
    * @param int                $int    Integer Comment
    * @param \Name\Spaced\Class $class  Class Comment
    * @return void
    */

**Comment by neild3r** [comment]
This is a planned feature

**Comment by petruavram** [comment]
@neild3r 

Please, please make a configuration for gap/separator between columns. I always use 2 spaces between doc tags and types or ` - ` before description.

Anyways, thank you for this extension, you've enabled me to switch to VS Code! 🎊

**Comment by jens1o** [comment]
I planned to do a pr where anyone can set what the person wants be before a tag, for example a tab using `\t`. Thoughts?

**Comment by petruavram** [comment]
@neild3r 

Yeah that'd be good I guess for people that use tabs for aligning (because you know tabs save so much storage and bandwidth that we'd be able to feed a 3rd world country /s) and would flow my boat as well. I think.

**Comment by Gert-dev** [comment]
Perhaps this can be done in stages, i.e. start by just aligning the names of the parameters. (Useful) Parameter descriptions always need to be written by hand anyway, so it could be done in another stage.

Maybe another question would be: is there anyone that _doesn't_ want at least the @param names to be aligned? I personally would never not align them, but I could be wrong. Still, if most people want it, the default could simply be reversed.

**Comment by neild3r** [comment]
Released as of v2.6.0
