### ISSUE TITLE
Nullable return types aren't parsed right

### ISSUE THREAD

**Issue by jens1o** [neild3r/vscode-php-docblocker#40]
![image](https://cloud.githubusercontent.com/assets/11234139/26254464/edbdd1ec-3cb6-11e7-87e9-23169b53aa1e.png)
I expect that `@return string|null` will be placed, not `void`, because that's wrong.

**Comment by jens1o** [comment]
Anyway, why is the default one `void`, and not `mixed`?

**Comment by neild3r** [comment]
Because if you have it as mixed, people will never actually change it and all of your projects functions return mixed

**Comment by jens1o** [comment]
okay.

**Comment by jens1o** [comment]
Okay, that makes sense.
