### ISSUE TITLE
how to show the time with php-docblocker.extra

### ISSUE THREAD

**Issue by plutokaito** [neild3r/vscode-php-docblocker#54]
whenever i create the doc or the function, i wanna to show the time, how can i do?

**Comment by jens1o** [comment]
That's not implemented yet, but not a bad idea.

@neild3r Thoughts? Are you fine with me creating a pr achieving this functionality?

**Comment by neild3r** [comment]
@jens1o happy for you to create a PR. However I'd recommend we look at some sort variable replacement system that will give us room to expand. Really we are just filling in some deficiencies in the number built in variables you can get from VS code.

**Comment by jens1o** [comment]
Okay, will do this as soon as I've got time. :)

**Comment by CallMeSirLiu** [comment]
I can't wait for it

**Comment by jens1o** [comment]
> . However I'd recommend we look at some sort variable replacement system that will give us room to expand.

I'm unsure how I should implement that, that's why I didn't filed a pr, yet. And I forgot to ask @neild3r ... sorry.

**Comment by neild3r** [comment]
This is probably now possible using the built in date stuff from vscode I will try it and post and example

**Comment by neild3r** [comment]
Ah this doesn't work right now because the snippet is built programmatically and the varianbles get escaped

**Comment by neild3r** [comment]
I've created a PR to make it use the built in snippets in the extra setting which will allow you to do this.

**Comment by chirag4396** [comment]
Just wanted to help to other Incase if someone landed on this page while finding a solution for adding a date and time under DocBlock.

I was able to achieve that by below setting,

```
"php-docblocker.extra": [
        "@createdAt $CURRENT_YEAR-$CURRENT_MONTH-$CURRENT_DATE $CURRENT_HOUR:$CURRENT_MINUTE:$CURRENT_SECOND"
    ]
```

but the only problem with this solution is that the "@createdAt" color was not highlight same as other variables(as in actual it is not a variable and I can understand that ;) ), but the rest worked as expected.

Thanks, @neild3r for adding an extra setting under extension :+1:
