### ISSUE TITLE
Support *short* syntax

### ISSUE THREAD

**Issue by beeblebrox3** [neild3r/vscode-php-docblocker#55]
Currently the docblock generation only support this format:

```php
<?php

class Foo {
    /**
     * Undocumented variable
     *
     * @var [type]
     */
    private $bar;
}
```

I use a lot like this:

```php
<?php

class Foo {
    /** @var [type] Undocumented variable */
    private $bar;
}
```

It's possible to support it?

**Comment by philipmclifton** [comment]
This is very useful for letting IDEs know more about vars. 

In Laravel often you can have:

`
/** @var UserRepository $userRepository */
$userRepository = app(UserRepository::class);
`

**Comment by wunc** [comment]
I believe this is a duplicate of #42

**Comment by beeblebrox3** [comment]
@wunc you are right! I'm closing this.
