### ISSUE TITLE
Autocomplete for function returning reference does not work properly

### ISSUE THREAD

**Issue by PrinsEdje80** [neild3r/vscode-php-docblocker#57]
VSC 1.15.1
PHP DocBlocker 1.2.0

Create a PHP function like this in a class:
```PHP
public function &someFunction() {
  return TRUE;
}
```
or a regulare function like this:
```PHP
function &someFunction() {
  return TRUE;
}
```
Start with the shortcut `/**` and only the most basic PHPDoc beginning will be put there
```PHP
/**
 *
 */
```
Whereas I expect to get
```PHP
/**
 * Undocumented function
 *
 * @return void
 */
```
which is what you get if you remove the `&`.

**Comment by jens1o** [comment]
Seems to be a missing regex match...

**Comment by PrinsEdje80** [comment]
Yeah, I would have figured something like that... But I have no clue about writing plugins for Visual Studio Code ;).

**Comment by neild3r** [comment]
This will be fixed in the next release
