### ISSUE TITLE
Make a list of supported tags in README.MD

### ISSUE THREAD

**Issue by romash1408** [neild3r/vscode-php-docblocker#61]
As I can see, this extension can only work with @param, @type, @returns, @throws tags, am I right?
If yes it would be helpful for beginners in phpdoc to place list of supported tags into readme file.
I just tried to understand why is my @see tag not working for halfhour, thinking that I just used wrong syntax...

**Comment by neild3r** [comment]
It should work worth more than those. There is a complete list in the code but it would probably be useful to list them in the readme, usually if you typing the @ and the first letter it should start giving you the completion list.

https://github.com/neild3r/vscode-php-docblocker/blob/master/src/completions.ts#L14-L147

**Comment by agung-wete** [comment]
how about add other annotations ? from popular package like symfony, doctrine etc
