### ISSUE TITLE
[Request] Flag to disable @return void

### ISSUE THREAD

**Issue by JasonHoffmann** [neild3r/vscode-php-docblocker#69]
Not sure if this would be useful to other folks, but the coding standards I follow does not require `@return void`. Wondering if it would be possible to add a flag to simply output nothing if the return type is void.

**Comment by neild3r** [comment]
Agreed. The only reason I keep it in is because when you're not using PHP7 return types we can't easily get the return type so often there is one that needs to be filled in manually but I can see an argument for turning this off.
