### ISSUE TITLE
useShortNames is not working

### ISSUE THREAD

**Issue by sarcastron** [neild3r/vscode-php-docblocker#71]
Thank you for a very helpful extension. I am having an issue with the `useShortNames` feature. Despite having the `useShortNames` value set to false, it is still using short names.

My settings have this key/value pair:

```
"php-docblocker.useShortNames": false
```

When I create a docblock types like `int` and `bool` continue using the short name:

```php
    /**
     * Example
     *
     * @param int    $num
     * @param bool $someBooleanVar
     * @return void
     */
```

I was expecting the result to look like this: 

```php
    /**
     * Example
     *
     * @param integer  $num
     * @param boolean $someBooleanVar
     * @return void
     */
```

**Comment by sarcastron** [comment]
I have a fix for this. I'll submit a PR as soon as I get tests written.

**Comment by neild3r** [comment]
This is because at the moment we aren't transforming PHP7 type hints and return types back into the long form but arguably we should. I'll create a PR

**Comment by neild3r** [comment]
@sarcastron, I've made a PR and which is now ready to merge. I will merge and do a release before xmas :)

**Comment by sarcastron** [comment]
Thank you so much!
