### ISSUE TITLE
I want to use datetime in the docblock, what should I do?

### ISSUE THREAD

**Issue by yiranzai** [neild3r/vscode-php-docblocker#74]
I am a phper from China.
First of all, I am very grateful to the development team for their contributions. I really like this extension.
However, I encountered a problem in the process of using it, and I found that this extension does not seem to support the datetime when the system was called.
Is there any alternative?

**Comment by 62006464** [comment]
你看看这个
https://github.com/neild3r/vscode-php-docblocker/issues/54

**Comment by yiranzai** [comment]
@neild3r  good job
