### ISSUE TITLE
Suggestions for default templates

### ISSUE THREAD

**Issue by areirei** [neild3r/vscode-php-docblocker#87]
- PHP version 7.2
- Visual Studio Code Version 1.24.0
- Extension: PHPDocBlocker version 1.6.0
- Extension: phpcs version 1.0.5

When i used `"php-docblocker.extra": ["@category ","@package  ","@author   ","@license ","@link     "],`
It looks like  that 
```
/**
 * Undocumented class
 *
 * @category 
 * @package  
 * @author   
 * @license 
 * @link     
 */
```

PHPDocBlocker is great :+1:  But not enough to get through the code Sniffer.

## One suggestion : Class default template
```
/**
 * Undocumented class
 * 
 * @category Description
 * @package  Category
 * @author   Name <email@email.com>
 * @license  http://url.com MIT
 * @link     http://url.com
 */
```

## One other suggestion : File default template
```
/**
 * Undocumented file
 * 
 * PHP version 7.2
 * 
 * @category Description
 * @package  Category
 * @author   Name <email@email.com>
 * @license  http://url.com MIT
 * @link     http://url.com
 */

```

Is it possible to set default annotations for an object?
Thanks for watching！

**Comment by neild3r** [comment]
It should be possible to do something like this as you can put placeholders in the extra config array. The current problem is the extra applies to both classes and functions so maybe the feature that you are looking for here is a class extra config option.

**Comment by vyskoczilova** [comment]
+1, 

I would love to define the current version which I can update every time I need to increase the version for the project? Like this, I have to think about it. Or is it already possible?

**Comment by neild3r** [comment]
@areirei @vyskoczilova See PR #98 this should provide the functionality you want once released

**Comment by neild3r** [comment]
@areirei @vyskoczilova you should have more flexibility for this in v2.0.0
