### ISSUE TITLE
How can i configure @author tag?

### ISSUE THREAD

**Issue by RGuerreroC** [neild3r/vscode-php-docblocker#88]
Hi all,

I wrote in my user config file this
```
php-docblocker.author": {
        "name": "rguerrero",
        "email": "my@email.es"
    },
    "php-docblocker.extra": ["@author ","@version 1.0"],
```
But when i invoke docbloker tag @author appears alone. I tried
`    "php-docblocker.extra": ["@author ${1: {{name}}} <$2: {{email}}}>","@version 1.0"],`
but at first placeholder appears "Undocumented function" and at second "[type]"

I'm using Marketplace version 1.6.0

I think i'm doing something wrong, can i get some help?

Thanks!

**Comment by maddog986** [comment]
Same problem here.

**Comment by neild3r** [comment]
It isn't set up to work with the extra tag system as that is much more simple.

Just hard code in the author for now when you change the author config you can just change in the extra tag as well.

```json
    "php-docblocker.extra": [
        "@author rguerrero <my@email.es>"
    ],
```

**Comment by RGuerreroC** [comment]
Thanks i'll try this!
