### ISSUE TITLE
Possibility  to remove the first line `Undocumented function`

### ISSUE THREAD

**Issue by dominikzogg** [neild3r/vscode-php-docblocker#90]
I would like the possibility to remove the first line `Undocumented function` by an option within settings

**Comment by neild3r** [comment]
@dominikzogg would you still want a placeholder there for entering text or would it be there is no text at all and no placeholder

**Comment by dominikzogg** [comment]
@neild3r i would prefer to be able to disable the row, but null as value to disable it or string to replace it's content would perfectly fine too

**Comment by neild3r** [comment]
@dominikzogg good idea. I'm going to try get in some updates over the Christmas period so I'll try to get this in too

**Comment by dominikzogg** [comment]
@neild3r thx

**Comment by neild3r** [comment]
@dominikzogg this should be possible with #98 as it allows control over the template and you could remove the message component entirely if you wished

**Comment by neild3r** [comment]
@dominikzogg this should now be possible as part of v2.0.0

**Comment by dominikzogg** [comment]
@neild3r can you give me a simple sample?

**Comment by neild3r** [comment]
@dominikzogg there should be an explanation in the [README.md](https://github.com/neild3r/vscode-php-docblocker)

**Comment by dominikzogg** [comment]
@neild3r i don't get howto disable a part of the phpdoc

**Comment by Fenweldryn** [comment]
Has anyone found a way to remove it?

**Comment by Fenweldryn** [comment]
Guys, I just found out how to do it. If anyone still need it just add this setting:

```
"php-docblocker.functionTemplate": {
        //"message": {},
        "return": {},
        "extra": {},
        "param": {},
    }
```

the commented message param is the culprit, just keep it out and you will be good to go!
