### ISSUE TITLE
Not documenting in 1.26.1?

### ISSUE THREAD

**Issue by carestad** [neild3r/vscode-php-docblocker#91]
I'm having problems getting docblocks in 1.26.0 of vscode. I have tried disabling all other extensions but it still won't automagically add blocks after I type `/**` above a function in my class.

I am also not quite sure how to debug this. No output in vscode's devtools or the extentions output bar. Any pointers would be appreciated :+1:

**Comment by carestad** [comment]
Edit title after 1.26.1 release. Still struggling.

**Comment by neild3r** [comment]
@carestad this could be similar to #44 as it's working fine for me on 1.26 have you got `editor.suggestOnTriggerCharacters` set to `true`?

You can still use it if not but you'd need to summon the suggestions manually after typing `/**` There is a keyboard shortcut to do so which on OSX at least by default is CTRL + Space bar

**Comment by neild3r** [comment]
Perhaps it's worth adding an optional keybinding so people can just assign a key combo instead

**Comment by kAlvaro** [comment]
> Perhaps it's worth adding an optional keybinding so people can just assign a key combo instead

There's currently no registered command to run from command palette, is there? A command itself would be a nice addition, whether it has a default keybinding or not.

**Comment by carestad** [comment]
Ugh, of course it was related to #44, AGAIN! Don't know how my settings have changed, but as of now I will at least leave comments in there so I know what will happen if I change them.

Having a registered command would be very nice as well, because now I have this plugin _and_ a jsdoc plugin (called "document this"), and both react to the same typing pattern.
