### ISSUE TITLE
Customize default template

### ISSUE THREAD

**Issue by oojacoboo** [neild3r/vscode-php-docblocker#97]
This is a great plugin, but I'm running into an issue that I don't seem to be able to resolve.

Firstly, with PHP7 and typing, the need for docblock has decreased drastically for us.  Interpreters can use the actual code to determine typing for params and returns.  This is awesome.  It doesn't mean docblock doesn't have a lot of value still, it does, just less so.

That all said, one of the things that I'm struggling with is the default template for docblock.  We don't include an `@return` dockblock annotation because it's usually redundant.  However, in cases where there is a mixed return type, we do add it, or if we need to add additional comments about the return value.

Therefore, I'm having to constantly delete the `@return` every time a dockblock is created.  It's a bit annoying and time consuming, especially when going back over legacy code and fixing commenting.

**Comment by neild3r** [comment]
@oojacoboo you can now disable the @return void by default by setting the config value `returnVoid` to false

**Comment by neild3r** [comment]
Also see #87 and #89 which are similar. It's quite a bit of a rework but should be possible to do to support all of these requests

**Comment by oojacoboo** [comment]
@neild3r awesome - looking forward to those updates!  I saw the option to disable `@return` for void.  However, this doesn't really help much for us, maybe only a little.

I think the best solution here is a default template setting that allows you to specify the default template generated.

**Comment by neild3r** [comment]
@oojacoboo there is a PR open #98 but one thing I found is that it needs to be a bit more clever about how it deals with gaps because it gets tricky for the template to understand where there should be gaps and if there should only be a gap if a certain tag exists so I haven't quite come up with a syntax for creating the template with this in mind.

**Comment by neild3r** [comment]
@oojacoboo this should now be configurable in v2.0.0
